### ISSUE TITLE
Failure to copy file - exception raised "Cannot get shell item for {path}"

### ISSUE THREAD

**Issue by smithps** [adam-nemeth/iPhoneImport#3]
Hi,
  I'm not a python programmer unfortunately, but am looking to copy files from my iPhone - It is an iPhone 13, running the Beta of 18.0 although I think the problem is with my Windows end, not the phone end. It seems to enumerate all of the folders (It finds 6867 files), creates the first directory on the Windows PC, but then has this exception which I have no clue how to resolve or even what is the cause.

Note that using the "Apple Devices" app from the Windows Store shows 3 .JPG photos in the folder 201512__

I hope you can help in some way. I do have access to a friend who is a python programmer and will see if he can look at it for me too.

Great work by the way! - Here is the last couple of rows of recursing the file system on the phone followed by the exception report. Please let me know if there's anything I can do for you.

```
Listing folder 'This PC\Apple iPhone\Internal Storage\201705__'
Listing folder 'This PC\Apple iPhone\Internal Storage\202403_y'
Listing folder 'This PC\Apple iPhone\Internal Storage\202403ca'
Import 6867 files
Traceback (most recent call last):
  File "C:\Users\PaulSmith\source\repos\iPhoneImport\win32utils.py", line 42, in get_shell_item_from_path
    return shell.SHCreateItemFromParsingName(path, None, shell.IID_IShellItem)
pywintypes.com_error: (-2147024894, 'The system cannot find the file specified.', None, None)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\PaulSmith\source\repos\iPhoneImport\__main__.py", line 125, in <module>
    main(parser.parse_args())
  File "C:\Users\PaulSmith\source\repos\iPhoneImport\__main__.py", line 111, in main
    copy_using_windows_shell(shell_items_to_copy_by_target_path, destination_path_str)
  File "C:\Users\PaulSmith\source\repos\iPhoneImport\__main__.py", line 72, in copy_using_windows_shell
    target_folder_shell_item = win32utils.get_shell_item_from_path(desination_folder)
  File "C:\Users\PaulSmith\source\repos\iPhoneImport\win32utils.py", line 44, in get_shell_item_from_path
    raise Exception(f"Cannot get shell item for {path}") from exception
Exception: Cannot get shell item for import\201512__
```

**Comment by adam-nemeth** [comment]
Hi,
Not sure what is going wrong. In line 71 of main the destination folder seems to have been created successfully, but when line 72 tries to open it with the Windows shell, that operation fails. What command did you run?

**Comment by smithps** [comment]
> Hi, Not sure what is going wrong. In line 71 of main the destination folder seems to have been created successfully, but when line 72 tries to open it with the Windows shell, that operation fails. What command did you run?

I think I sussed it with the help of my friend. I had entered a *relative* path for the destination - putting the full path in fixed the issue.

So, 

`python C:\Users\PaulSmith\source\repos\iPhoneImport "This PC\Apple iPhone\Internal Storage" ".\import"` does not work, but `python C:\Users\PaulSmith\source\repos\iPhoneImport "This PC\Apple iPhone\Internal Storage" "C:\Users\PaulSmith\source\repos\import"` does

**Comment by adam-nemeth** [comment]
I'm glad the issue has been resolved!
